name: Archive Android SDK

# Trigger the workflow on push to the main branch or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  archive-sdk:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository (optional, but recommended)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: (Optional) Set up Android SDK if not already present
      # Uncomment and configure the following step if you need to install the Android SDK
      # - name: Set Up Android SDK
      #   uses: android-actions/setup-android@v2
      #   with:
      #     sdk-version: 'latest'

      # Step 3: Archive the Android SDK directory
      - name: Archive Android SDK
        run: |
          # Define the source directory and the output archive name
          SDK_DIR="/usr/local/lib/android/sdk"
          ARCHIVE_NAME="sdk.tar.gz"

          # Check if the SDK directory exists
          if [ -d "$SDK_DIR" ]; then
            echo "Archiving $SDK_DIR into $ARCHIVE_NAME..."
            tar -czvf $ARCHIVE_NAME -C $(dirname $SDK_DIR) $(basename $SDK_DIR)
            echo "Archive created successfully."
          else
            echo "Error: Directory $SDK_DIR does not exist."
            exit 1
          fi

      # Step 4: Upload the archived SDK as an artifact
      - name: Upload SDK Archive
        uses: actions/upload-artifact@v3
        with:
          name: android-sdk-archive
          path: sdk.tar.gz
          retention-days: 1  # Optional: Specify how long to retain the artifact (default is 90 days)

